//! ★ Design r2 §5 — **stem is code, year is data, the filesystem is the registry.**
//!
//! [`Stem`] is the closed set of forms this crate can FILL — hand-written, because a new form needs a
//! filler and is correctly a code change. Everything else in this module is generated by `build.rs`
//! from the glob of `forms/<year>/`: [`template`], [`map_text`], [`BUNDLED_YEARS`], [`BUNDLED`]. A new
//! YEAR of an existing form is files under a directory and nothing else; a new form's files with no
//! [`Stem`] variant fail to compile (the generated `match` names a variant that does not exist),
//! which is the intended signal.
//!
//! Step 2 of design r2 §10: this module lands BESIDE the old `include_*!` consts and `for_year`
//! arms, with tests that the two agree byte-for-byte on every file. Step 3 switches the fillers over
//! and deletes the arms.
use std::fmt;

/// The closed set of forms this crate has a filler for — CODE, by design.
///
/// The variant name is derived from the file stem by one rule (`build.rs::variant_name`): capitalise
/// the first letter of each `_`-separated part and join — `f1040s1a` → `F1040s1a`, `schedule_d` →
/// `ScheduleD`. [`Stem::file_stem`] is the inverse and is what the tests hold to the files on disk.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Stem {
    /// Form 1040 — the return itself; no attachment sequence number.
    F1040,
    /// Schedule 1 (Form 1040) — Additional Income and Adjustments to Income.
    F1040s1,
    /// Schedule 1-A (Form 1040) — Additional Deductions (OBBBA, TY2025+). No filler yet.
    F1040s1a,
    /// Schedule 2 — Additional Taxes.
    F1040s2,
    /// Schedule 3 — Additional Credits and Payments.
    F1040s3,
    /// Schedule A — Itemized Deductions.
    F1040sa,
    /// Schedule B — Interest and Ordinary Dividends.
    F1040sb,
    /// Schedule C — Profit or Loss From Business.
    F1040sc,
    /// Form 6251 — Alternative Minimum Tax.
    F6251,
    /// Form 8275 — Disclosure Statement (periodic; Rev. 10-2024).
    F8275,
    /// Form 8283 — Noncash Charitable Contributions (periodic).
    F8283,
    /// Form 8949 — Sales and Other Dispositions of Capital Assets.
    F8949,
    /// Form 8959 — Additional Medicare Tax.
    F8959,
    /// Form 8960 — Net Investment Income Tax.
    F8960,
    /// Form 8995 — Qualified Business Income Deduction Simplified Computation.
    F8995,
    /// Form 8995-A — Qualified Business Income Deduction.
    F8995a,
    /// Schedule D (Form 1040) — Capital Gains and Losses. Crate stem `schedule_d`, IRS `f1040sd`.
    ScheduleD,
    /// Schedule SE (Form 1040) — Self-Employment Tax. Crate stem `schedule_se`, IRS `f1040sse`.
    ScheduleSe,
}

impl Stem {
    /// Every variant, in declaration order. Exhaustive by construction: the match in
    /// [`Stem::file_stem`] names every variant, and this list is checked against it by test.
    pub const ALL: &'static [Stem] = &[
        Stem::F1040,
        Stem::F1040s1,
        Stem::F1040s1a,
        Stem::F1040s2,
        Stem::F1040s3,
        Stem::F1040sa,
        Stem::F1040sb,
        Stem::F1040sc,
        Stem::F6251,
        Stem::F8275,
        Stem::F8283,
        Stem::F8949,
        Stem::F8959,
        Stem::F8960,
        Stem::F8995,
        Stem::F8995a,
        Stem::ScheduleD,
        Stem::ScheduleSe,
    ];

    /// The crate stem — the `.pdf` / `.map.toml` basename under `forms/<year>/`.
    pub fn file_stem(self) -> &'static str {
        match self {
            Stem::F1040 => "f1040",
            Stem::F1040s1 => "f1040s1",
            Stem::F1040s1a => "f1040s1a",
            Stem::F1040s2 => "f1040s2",
            Stem::F1040s3 => "f1040s3",
            Stem::F1040sa => "f1040sa",
            Stem::F1040sb => "f1040sb",
            Stem::F1040sc => "f1040sc",
            Stem::F6251 => "f6251",
            Stem::F8275 => "f8275",
            Stem::F8283 => "f8283",
            Stem::F8949 => "f8949",
            Stem::F8959 => "f8959",
            Stem::F8960 => "f8960",
            Stem::F8995 => "f8995",
            Stem::F8995a => "f8995a",
            Stem::ScheduleD => "schedule_d",
            Stem::ScheduleSe => "schedule_se",
        }
    }

    /// The inverse of [`Stem::file_stem`]; `None` for a stem this crate has no filler for.
    pub fn from_file_stem(s: &str) -> Option<Stem> {
        Stem::ALL.iter().copied().find(|st| st.file_stem() == s)
    }
}

impl fmt::Display for Stem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.file_stem())
    }
}

// The generated bindings: `template`, `map_text`, `BUNDLED_YEARS`, `BUNDLED`.
include!(concat!(env!("OUT_DIR"), "/bundled.rs"));

/// Every tax year with a bundled form. Derived from the glob — the replacement for `SUPPORTED_YEARS`.
pub fn bundled_years() -> &'static [i32] {
    BUNDLED_YEARS
}

/// The bundled years as English for a refusal message — `"2017, 2024 and 2025"` — so no message
/// ever carries a year literal again.
pub fn years_sentence() -> String {
    let ys: Vec<String> = BUNDLED_YEARS.iter().map(|y| y.to_string()).collect();
    match ys.len() {
        0 => "no tax year".to_string(),
        1 => ys[0].clone(),
        n => format!("{} and {}", ys[..n - 1].join(", "), ys[n - 1]),
    }
}

/// ★ A PERIODIC form's template for a year that has no file of its own (design r2 §4 `versioning`).
///
/// An annual form exists per year or not at all. A periodic form (Form 8275 Rev. 10-2024, Form 8283
/// Rev. 12-2025) is revised on its own calendar, and the IRS's instruction is to file the CURRENT
/// revision — so a tax year with no `forms/<year>/<stem>.pdf` of its own is served by the **newest
/// bundled revision**, and only when that file's own row says `versioning = { periodic = … }`. An
/// annual form never aliases: `None`.
///
/// Returns the bytes and the year directory they came from, so the caller can license the alias by
/// hash (`Form8275Map::alias_is_licensed_by`) and restamp the map's `year`.
pub fn periodic_template(stem: Stem, year: i32) -> Option<(&'static [u8], i32)> {
    if let Some(own) = template(stem, year) {
        return Some((own, year));
    }
    // A tax year this build bundles nothing for is refused everywhere — a periodic alias serves the
    // BUNDLED years that lack their own file, never a year outside the package.
    if !BUNDLED_YEARS.contains(&year) {
        return None;
    }
    let newest = BUNDLED
        .iter()
        .filter(|(s, _)| *s == stem)
        .map(|(_, y)| *y)
        .max()?;
    let row = crate::map::MapRow::read(map_text(stem, newest)?).ok()?;
    match row.versioning {
        crate::map::Versioning::Periodic { .. } => Some((template(stem, newest)?, newest)),
        crate::map::Versioning::Annual(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};

    fn forms_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("forms")
    }

    /// The glob on disk, derived here independently of build.rs, so the two can disagree.
    fn on_disk() -> Vec<(String, i32)> {
        let mut out = Vec::new();
        for y in std::fs::read_dir(forms_root()).unwrap().flatten() {
            if !y.path().is_dir() {
                continue;
            }
            let year: i32 = y.file_name().to_string_lossy().parse().unwrap();
            for f in std::fs::read_dir(y.path()).unwrap().flatten() {
                let name = f.file_name().to_string_lossy().to_string();
                if let Some(stem) = name.strip_suffix(".map.toml") {
                    out.push((stem.to_string(), year));
                }
            }
        }
        out.sort();
        out
    }

    /// ★ The build script binds EVERY file on disk, byte-for-byte — and nothing that is not on disk.
    #[test]
    fn the_generated_bindings_are_the_files_on_disk_both_ways() {
        let disk = on_disk();
        assert!(disk.len() >= 37, "walk found {}", disk.len());
        let mut bound: Vec<(String, i32)> = BUNDLED
            .iter()
            .map(|(s, y)| (s.file_stem().to_string(), *y))
            .collect();
        bound.sort();
        assert_eq!(
            bound, disk,
            "BUNDLED ≠ the glob: the build script missed or invented a file"
        );
        for (stem_s, year) in &disk {
            let stem = Stem::from_file_stem(stem_s).unwrap_or_else(|| {
                panic!("{stem_s}: on disk but no `Stem` variant — add the filler")
            });
            let pdf = std::fs::read(
                forms_root()
                    .join(year.to_string())
                    .join(format!("{stem_s}.pdf")),
            )
            .unwrap();
            let map = std::fs::read_to_string(
                forms_root()
                    .join(year.to_string())
                    .join(format!("{stem_s}.map.toml")),
            )
            .unwrap();
            assert_eq!(
                template(stem, *year),
                Some(pdf.as_slice()),
                "{year}/{stem_s}.pdf"
            );
            assert_eq!(
                map_text(stem, *year),
                Some(map.as_str()),
                "{year}/{stem_s}.map.toml"
            );
        }
        // A pair the glob did not find is None, never a stale binding.
        assert_eq!(template(Stem::F6251, 2017), None);
        assert_eq!(map_text(Stem::F1040s1a, 2024), None);
    }

    #[test]
    fn bundled_years_are_the_year_directories() {
        let mut dirs: Vec<i32> = std::fs::read_dir(forms_root())
            .unwrap()
            .flatten()
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().parse().unwrap())
            .collect();
        dirs.sort();
        assert_eq!(bundled_years(), dirs.as_slice());
        assert_eq!(
            bundled_years(),
            &[2017, 2024, 2025],
            "three years on disk today"
        );
    }

    /// `Stem::ALL` and `file_stem` are two views of one set; a variant added to one and not the other
    /// reds here (the `match` in `file_stem` is exhaustive, so the compiler covers that direction).
    #[test]
    fn every_stem_round_trips_through_its_file_stem() {
        for s in Stem::ALL {
            assert_eq!(Stem::from_file_stem(s.file_stem()), Some(*s));
            assert_eq!(s.to_string(), s.file_stem());
        }
        let mut names: Vec<&str> = Stem::ALL.iter().map(|s| s.file_stem()).collect();
        names.sort();
        names.dedup();
        assert_eq!(
            names.len(),
            Stem::ALL.len(),
            "two variants share a file stem"
        );
    }
}
