//! ★ Design r2 §5 — **the binding is a build script, and it decides NOTHING.**
//!
//! It globs `forms/<year>/` under this crate's own manifest directory (never anywhere else — the
//! publishing trap: an `include_*!` that reaches outside the crate ships a broken tarball with exit
//! 0) and emits `bundled.rs` into `OUT_DIR`: one `include_bytes!` per template, one `include_str!`
//! per map, the list of years found, and the list of `(Stem, year)` pairs. Every judgment about a
//! form lives in the map's ROW (`MapRow`, design r2 §4), written by a human; every filler is code.
//!
//! The `Stem` enum is HAND-WRITTEN in `src/bundled.rs` (a new FORM needs a filler and is correctly a
//! code change). This script derives the variant name from the file stem by one rule; a stem with no
//! variant makes the generated code fail to compile, which is the intended signal: "you added a form
//! without adding its filler". A new YEAR of an existing form is files under a directory and nothing
//! else.
//!
//! What it refuses (a build error, not a silent skip): a year directory that is not four digits; a
//! `.pdf` with no `.map.toml` beside it or a map with no PDF — location is status (§3), and an
//! unpaired file is a form the crate would list and could not fill.
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn variant_name(stem: &str) -> String {
    // `f1040s1a` → `F1040s1a`; `schedule_d` → `ScheduleD`; `schedule_se` → `ScheduleSe`.
    stem.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let forms = manifest_dir.join("forms");
    println!("cargo:rerun-if-changed=forms");

    // year → stem → (has_pdf, has_map)
    let mut found: BTreeMap<i32, BTreeMap<String, (bool, bool)>> = BTreeMap::new();
    let mut year_records: Vec<(i32, PathBuf)> = Vec::new();
    let mut year_dirs: Vec<PathBuf> = std::fs::read_dir(&forms)
        .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", forms.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    year_dirs.sort();
    for dir in &year_dirs {
        let name = dir.file_name().unwrap().to_string_lossy().to_string();
        let year: i32 = match (name.len(), name.parse::<i32>()) {
            (4, Ok(y)) => y,
            _ => panic!(
                "build.rs: `forms/{name}/` is not a four-digit tax year — the year package's location IS its \
                 status (design r2 §3), and a directory that is not a year is a form outside every gate"
            ),
        };
        println!("cargo:rerun-if-changed={}", dir.display());
        // ★ Design r2 §6 — the YEAR RECORD. A year directory without one is a year with no declared
        //   intent (no expected form set, no due date, no oracle, no regime) — refused at build.
        let record = dir.join("YEAR.toml");
        if !record.is_file() {
            panic!(
                "build.rs: forms/{name}/ has no YEAR.toml — every bundled year declares itself (design r2 §6: \
                 status, return_due, forms_expected, forms_absent, tables, oracles, prices_through, \
                 information_returns). Location is status; a year without a record is a form outside every gate."
            );
        }
        year_records.push((year, record));
        let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .collect();
        files.sort();
        for f in files {
            println!("cargo:rerun-if-changed={}", f.display());
            let fname = f.file_name().unwrap().to_string_lossy().to_string();
            let entry = found.entry(year).or_default();
            if let Some(stem) = fname.strip_suffix(".map.toml") {
                entry.entry(stem.to_string()).or_default().1 = true;
            } else if let Some(stem) = fname.strip_suffix(".pdf") {
                entry.entry(stem.to_string()).or_default().0 = true;
            }
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by build.rs from the glob of `forms/<year>/` — do not edit."
    )
    .unwrap();
    writeln!(
        out,
        "// Every judgment about a form is in its map's ROW; this file only binds files."
    )
    .unwrap();
    let mut pairs: Vec<(i32, String)> = Vec::new();
    for (year, stems) in &found {
        for (stem, (has_pdf, has_map)) in stems {
            if !(*has_pdf && *has_map) {
                panic!(
                    "build.rs: forms/{year}/{stem} has {} — a template without a map (or a map without a \
                     template) is a form the crate would list and could not fill. Location is status: \
                     both files, or neither.",
                    if *has_pdf { "a .pdf but no .map.toml" } else { "a .map.toml but no .pdf" }
                );
            }
            pairs.push((*year, stem.clone()));
        }
    }
    // template()
    writeln!(
        out,
        "\n/// The bundled PDF for `(stem, year)`, or `None` when this build carries no such file."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn template(stem: Stem, year: i32) -> Option<&'static [u8]> {{"
    )
    .unwrap();
    writeln!(out, "    match (stem, year) {{").unwrap();
    for (year, stem) in &pairs {
        let p: &Path = &forms.join(year.to_string()).join(format!("{stem}.pdf"));
        writeln!(
            out,
            "        (Stem::{}, {year}) => Some(include_bytes!({:?})),",
            variant_name(stem),
            p.display().to_string()
        )
        .unwrap();
    }
    writeln!(out, "        _ => None,\n    }}\n}}").unwrap();
    // map_text()
    writeln!(out, "\n/// The committed map (TOML text) for `(stem, year)`, or `None` when this build carries none.").unwrap();
    writeln!(
        out,
        "pub fn map_text(stem: Stem, year: i32) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out, "    match (stem, year) {{").unwrap();
    for (year, stem) in &pairs {
        let p: &Path = &forms
            .join(year.to_string())
            .join(format!("{stem}.map.toml"));
        writeln!(
            out,
            "        (Stem::{}, {year}) => Some(include_str!({:?})),",
            variant_name(stem),
            p.display().to_string()
        )
        .unwrap();
    }
    writeln!(out, "        _ => None,\n    }}\n}}").unwrap();
    // years + pairs
    let years: Vec<String> = found.keys().map(|y| y.to_string()).collect();
    writeln!(out, "\n/// Every tax year with at least one bundled form — DERIVED from `forms/`, replacing `SUPPORTED_YEARS`.").unwrap();
    writeln!(
        out,
        "pub const BUNDLED_YEARS: &[i32] = &[{}];",
        years.join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "\n/// Every `(Stem, year)` this build binds — the row SET, as the glob found it."
    )
    .unwrap();
    writeln!(out, "pub const BUNDLED: &[(Stem, i32)] = &[").unwrap();
    for (year, stem) in &pairs {
        writeln!(out, "    (Stem::{}, {year}),", variant_name(stem)).unwrap();
    }
    writeln!(out, "];").unwrap();

    // year_record_text()
    writeln!(out, "\n/// The committed `forms/<year>/YEAR.toml` text — the year's DECLARATION (design r2 §6).").unwrap();
    writeln!(
        out,
        "pub fn year_record_text(year: i32) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out, "    match year {{").unwrap();
    for (year, path) in &year_records {
        writeln!(
            out,
            "        {year} => Some(include_str!({:?})),",
            path.display().to_string()
        )
        .unwrap();
    }
    writeln!(out, "        _ => None,\n    }}\n}}").unwrap();

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("bundled.rs");
    std::fs::write(&dest, out)
        .unwrap_or_else(|e| panic!("build.rs: cannot write {}: {e}", dest.display()));
}
