.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-reject-conflict 1  btctax "btctax manual"
.SH NAME
reject\-conflict \- Reject an import conflict
.SH SYNOPSIS
\fBreject\-conflict\fR [\fB\-h\fR|\fB\-\-help\fR] <\fICONFLICT\fR> 
.SH DESCRIPTION
Reject an import conflict
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICONFLICT\fR>

