.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-verify 1  btctax "btctax manual"
.SH NAME
verify \- FR9 integrity check (non\-zero exit on hard blockers)
.SH SYNOPSIS
\fBverify\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
FR9 integrity check (non\-zero exit on hard blockers)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
