.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-classify-inbound-gift 1  btctax "btctax manual"
.SH NAME
classify\-inbound\-gift \- Classify an inbound TransferIn as a received gift
.SH SYNOPSIS
\fBclassify\-inbound\-gift\fR <\fB\-\-fmv\-at\-gift\fR> [\fB\-\-donor\-basis\fR] [\fB\-\-donor\-acquired\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIN_REF\fR> 
.SH DESCRIPTION
Classify an inbound TransferIn as a received gift
.SH OPTIONS
.TP
\fB\-\-fmv\-at\-gift\fR \fI<FMV_AT_GIFT>\fR

.TP
\fB\-\-donor\-basis\fR \fI<DONOR_BASIS>\fR

.TP
\fB\-\-donor\-acquired\fR \fI<DONOR_ACQUIRED>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIN_REF\fR>

