.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-safe-harbor-allocate 1  btctax "btctax manual"
.SH NAME
safe\-harbor\-allocate \- Path\-B safe\-harbor allocate (from the actual pre\-2025 position)
.SH SYNOPSIS
\fBsafe\-harbor\-allocate\fR [\fB\-\-method\fR] [\fB\-\-attest\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Path\-B safe\-harbor allocate (from the actual pre\-2025 position)
.SH OPTIONS
.TP
\fB\-\-method\fR \fI<METHOD>\fR [default: actual]

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
actual
.IP \(bu 2
pro\-rata
.RE
.TP
\fB\-\-attest\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
