.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-safe-harbor-attest 1  btctax "btctax manual"
.SH NAME
safe\-harbor\-attest \- Attest an existing allocation as timely
.SH SYNOPSIS
\fBsafe\-harbor\-attest\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Attest an existing allocation as timely
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
