.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-classify-inbound-income 1  btctax "btctax manual"
.SH NAME
classify\-inbound\-income \- Classify an inbound TransferIn as income
.SH SYNOPSIS
\fBclassify\-inbound\-income\fR <\fB\-\-kind\fR> [\fB\-\-fmv\fR] [\fB\-\-business\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIN_REF\fR> 
.SH DESCRIPTION
Classify an inbound TransferIn as income
.SH OPTIONS
.TP
\fB\-\-kind\fR \fI<KIND>\fR

.TP
\fB\-\-fmv\fR \fI<FMV>\fR

.TP
\fB\-\-business\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIN_REF\fR>

