.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-optimize-run 1  btctax "btctax manual"
.SH NAME
run \- Mode\-1 what\-if: print the tax\-saving lot\-selection proposal. NOTHING is filed or bound
.SH SYNOPSIS
\fBrun\fR <\fB\-\-tax\-year\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Mode\-1 what\-if: print the tax\-saving lot\-selection proposal. NOTHING is filed or bound
.SH OPTIONS
.TP
\fB\-\-tax\-year\fR \fI<TAX_YEAR>\fR
The tax year to optimize (must be 2025 or later)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
