.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-import 1  btctax "btctax manual"
.SH NAME
import \- Import one or more export files (auto\-groups Swan)
.SH SYNOPSIS
\fBimport\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIFILES\fR] 
.SH DESCRIPTION
Import one or more export files (auto\-groups Swan)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIFILES\fR]

