.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-accept-conflict 1  btctax "btctax manual"
.SH NAME
accept\-conflict \- Accept an import conflict
.SH SYNOPSIS
\fBaccept\-conflict\fR [\fB\-h\fR|\fB\-\-help\fR] <\fICONFLICT\fR> 
.SH DESCRIPTION
Accept an import conflict
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICONFLICT\fR>

