.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-link-transfer 1  btctax "btctax manual"
.SH NAME
link\-transfer \- Confirm a self\-transfer (TransferLink)
.SH SYNOPSIS
\fBlink\-transfer\fR [\fB\-\-to\-event\fR] [\fB\-\-to\-wallet\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIOUT\fR> 
.SH DESCRIPTION
Confirm a self\-transfer (TransferLink)
.SH OPTIONS
.TP
\fB\-\-to\-event\fR \fI<TO_EVENT>\fR

.TP
\fB\-\-to\-wallet\fR \fI<TO_WALLET>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOUT\fR>

