.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-void 1  btctax "btctax manual"
.SH NAME
void \- Void a revocable decision
.SH SYNOPSIS
\fBvoid\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITARGET\fR> 
.SH DESCRIPTION
Void a revocable decision
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITARGET\fR>

