.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH btctax-reconcile-set-fmv 1  btctax "btctax manual"
.SH NAME
set\-fmv \- Set a manual FMV on an event
.SH SYNOPSIS
\fBset\-fmv\fR <\fB\-\-fmv\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIEVENT\fR> 
.SH DESCRIPTION
Set a manual FMV on an event
.SH OPTIONS
.TP
\fB\-\-fmv\fR \fI<FMV>\fR
Fair\-market value of the BTC at the event date — USD dollars, NOT sats
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIEVENT\fR>
The event reference to set the FMV on (see `btctax events list`)
